name: aws.server.js CI

on:
  push:
    branches: [main]
    paths:
      - "**" # Triggers workflow for any changes

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, aws-server]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: 🚀 Checkout Code
        uses: actions/checkout@v2

      - name: 📦 Create `.env` File for Backend
        run: |
          cd backend
          touch .env
          echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> .env
          echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo REACT_APP_SERVER_URL=${{ secrets.REACT_APP_SERVER_URL }} >> .env
          echo GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} >> .env
          cat .env

      - name: 📦 Create `.env` File for Frontend
        run: |
          cd frontend
          touch .env
          echo REACT_APP_SERVER_URL=${{ secrets.REACT_APP_SERVER_URL }} >> .env
          echo ENVIRONMENT=${{ secrets.ENVIRONMENT }} >> .env
          cat .env 

      - name: 🔧 Set Up Node.js (Backend)
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: 📦 Install Backend Dependencies
        run: |
          cd backend
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: 🔧 Set Up Node.js (Frontend)
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: 📦 Install Frontend Dependencies & Build
        run: |
          cd frontend
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
          npm run build

      - name: 🔄 Deploy to Server & Restart Services
        run: |
          cd backend
          pm2 restart all

          cd ../frontend
          npm run build
          sudo cp -r build/* /var/www/html/
